Repository k1LoW/octocov, pull requests merged in 2023-09, with the labels that each got.

#249 Show custom metrics reports in pull requests and summaries
  .github/workflows/ci.yml
  cmd/comment.go
  pkg/coverage/coverage_test.go
  pkg/coverage/diff.go
  pkg/ratio/ratio.go
  pkg/ratio/ratio_test.go
  report/custom.go
  report/custom_test.go
  report/diff_report.go
  report/diff_report_test.go
  report/report.go
  report/report_test.go
  testdata/actions/coverage/Dockerfile
  testdata/custom_metrics/benchmark_0.json
  testdata/custom_metrics/benchmark_1.json
  testdata/custom_metrics/custom_metric_set_out.0.golden
  testdata/custom_metrics/custom_metric_set_out.1.golden
  testdata/custom_metrics/custom_metric_set_out.2.golden
  testdata/custom_metrics/custom_metric_set_table.0.golden
  testdata/custom_metrics/custom_metric_set_table.1.golden
  testdata/custom_metrics/custom_metric_set_table.2.golden
  testdata/diff_out.golden
  testdata/diff_table.golden
Labels: enhancement, minor, breaking-change

#252 Show custom metrics reports in output of `octocov`
  cmd/root.go
  report/custom.go
  report/json.go
  report/report.go
  report/report_test.go
  testdata/custom_metrics/benchmark_0.json
  testdata/custom_metrics/benchmark_1.json
  testdata/custom_metrics/custom_metric_set_out.1.golden
  testdata/custom_metrics/custom_metric_set_out.2.golden
Labels: enhancement

#254 Add JSON Schema for custom metrics
  Makefile
  go.mod
  go.sum
  report/custom.go
  report/custom_metrics_schema.json
  report/custom_test.go
  report/report.go
  testdata/actions/collect/Dockerfile
Labels: enhancement

#259 Support for multiple custom metrics from one environment variable.
  README.md
  report/report.go
  report/report_test.go
  testdata/custom_metrics/benchmark_0_1.json
Labels: enhancement

#261 If the value of custom metric is determined to be an integer, the metric is displayed as an integer
  report/custom.go
  testdata/custom_metrics/custom_metric_set_out.1.golden
  testdata/custom_metrics/custom_metric_set_out.2.golden
  testdata/custom_metrics/custom_metric_set_table.1.golden
  testdata/custom_metrics/custom_metric_set_table.2.golden
  testdata/custom_metrics/diff_custom_metric_set_table.0.golden
  testdata/custom_metrics/diff_custom_metric_set_table.1.golden
Labels: enhancement, breaking-change

#266 Fix diff metrics table (panic: runtime error: invalid memory address or nil pointer dereference)
  report/custom.go
Labels: bug

#268 swap fileA and fileB results because it was reversed
  report/diff_report.go
Labels: bug

#270 Support metadata for custom metrics
  cmd/comment.go
  report/custom.go
  report/custom_test.go
  report/report_test.go
  testdata/custom_metrics/benchmark_0.json
  testdata/custom_metrics/benchmark_0_1.json
  testdata/custom_metrics/benchmark_1.json
  testdata/custom_metrics/custom_metric_set_metadata_table.0.golden
  testdata/custom_metrics/custom_metric_set_metadata_table.1.golden
  testdata/custom_metrics/diff_custom_metric_set_metadata_table.0.golden
  testdata/custom_metrics/diff_custom_metric_set_metadata_table.1.golden
Labels: enhancement

#277 Update linter setting
  .github/workflows/ci.yml
  .golangci.yml
  .gostyle.yml
  Makefile
  central/central.go
  central/central_test.go
  cmd/badge.go
  cmd/comment.go
  cmd/dump.go
  cmd/init.go
  cmd/lsFiles.go
  cmd/migrateBqTable.go
  cmd/root.go
  cmd/summary.go
  cmd/view.go
  config/build.go
  config/config.go
  config/config_test.go
  config/generate.go
  config/ready_test.go
  config/yaml.go
  datastore/artifact/artifact.go
  datastore/bq/bq.go
  datastore/datastore.go
  datastore/datastore_test.go
  datastore/gcs/gcs.go
  datastore/mackerel/mackerel.go
  gh/gh.go
  gh/gh_test.go
  internal/path.go
  internal/path_test.go
  main.go
  pkg/badge/badge.go
  pkg/coverage/coverage.go
  pkg/coverage/coverage_test.go
  pkg/coverage/jacoco.go
  pkg/coverage/lcov.go
  pkg/coverage/merge_test.go
  pkg/coverage/printer.go
  pkg/coverage/simplecov.go
  pkg/pplang/pplang.go
  pkg/pplang/pplang_test.go
  pkg/ratio/copy_from_gocloc.go
  pkg/ratio/merge.go
  pkg/ratio/merge_test.go
  pkg/ratio/ratio.go
  pkg/ratio/ratio_test.go
  report/custom.go
  report/diff_report.go
  report/report.go
  report/report_test.go
  version/version.go
Labels: minor, breaking-change

#279 Support `if:` section for three metrics
  README.md
  config/config.go
  config/ready.go
Labels: enhancement

#280 Delete/Minimize previous comments all
  gh/gh.go
Labels: bug

#282 Always override existing environment variables with the prefix `OCTOCOV_`
  README.md
  main.go
Labels: minor, breaking-change
