Repository k1LoW/octocov, pull requests merged in 2025-09, with the labels that each got.

#536 Display not modified/but affected files in file coverage
  central/central_test.go
  report/diff_report.go
  report/diff_report_test.go
  testdata/central_README.md.golden
  testdata/diff_file_coverages_table.golden
  testdata/reports/k1LoW/octocov/report1.json
  testdata/reports/k1LoW/octocov/report2.json
Labels: enhancement, minor, breaking-change

#542 fix: DiffReport.FileCoveragesTable file name & path
  cmd/comment.go
  report/diff_report.go
  report/diff_report_test.go
Labels: bug

#545 fix: fix GitRoot in config
  config/build.go
Labels: bug

#564 fix: support artifact re-upload
  .github/workflows/ci.yml
  datastore/artifact/artifact.go
  gh/gh.go
Labels: minor
