Repository k1LoW/octocov, pull requests merged in 2025-02, with the labels that each got.

#448 chore: Update go directive version
  go.mod
  go.sum
Labels: dependencies

#456 chore(deps): update Go version to 1.23.6 in go.mod
  go.mod
Labels: minor, dependencies, go

#460 fix(deps): update goccy/go-yaml
  config/testdata/central_push_enabled_octocov.yml
  config/yaml.go
  go.mod
  go.sum
Labels: documentation, minor, breaking-change, go

#463 Upgrade go-github (and the dependants) and pass name option
  config/ready_test.go
  gh/gh.go
  gh/gh_test.go
  go.mod
  go.sum
  pplang/pplang.go
  pplang/pplang_test.go
Labels: minor
